#!/usr/bin/env bash

HOST_IP=`/sbin/ip route|awk '/default/ { print $3 }'`

echo "xdebug.remote_host=$HOST_IP" >> /usr/local/etc/php/conf.d/xdebug-php.ini

mv /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini.back /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

php $@
