#!/usr/bin/env bash

composer --version

drupal --version

symfony --version

echo `drush --version`
echo "Docker Console `dcon --version`"

php --version

docker-php-ext-enable xdebug

cp ${PHP_INI_DIR}/conf.d/xdebug-php.ini.back ${PHP_INI_DIR}/conf.d/xdebug-php.ini

echo "xdebug.remote_host=$HOST_IP" >> ${PHP_INI_DIR}/conf.d/xdebug-php.ini

php -r 'foreach (get_loaded_extensions() as $extension) echo "$extension: " . phpversion($extension) . "\n";' | grep xdebug
php -r 'foreach (get_loaded_extensions() as $extension) echo "$extension: " . phpversion($extension) . "\n";' | grep imagick

rm ${PHP_INI_DIR}/conf.d/xdebug-php.ini
rm ${PHP_INI_DIR}/conf.d/docker-php-ext-xdebug.ini

python --version
